 pipeline {
        agent {
                label 'sonar'
               }
        stages {
          stage("build & SonarQube analysis") { 
            steps {
              git branch: 'development_devops', credentialsId: 'Gitlab_test', url: 'git@osigitlab.osius.com:internal-projects/osi-one/osi-one-ui-a7.git'
              withSonarQubeEnv('sonarserver') {
                sh '/opt/sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner -Dsonar.branch=development02'
              }
            }
          }
          stage("Quality Gate") {
            steps {
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: false
              }
            }
          }
          stage("Sending Artifact to Nexus ") {
            steps {
                script{
                    sh "npm install"
                    sh "npm install ng2-ckeditor@1.3.1"  
                    sh "node --max-old-space-size=4096 node_modules/@angular/cli/bin/ng build --configuration=dev"
                    sh "npm publish --registry=http://192.168.32.188:8081/repository/osi-one-ui-a7/"
                     }
                 } 
            }
          }
    }
