export class profileDetails{
    constructor(
        public contactNumber1:any,
        public contactNumber2:any,
        public creationDate:any,
        public currentCtc:any,
        public currentLocation:any,
        public currentOrganization:any,
        public emailId1:any,
        public emailId2:any,
        public expectedCtc:any,
        public expectedDoj:any,
        public externalRefBu:any,
        public externalRefId:any,
        public firstName:any,
        public fullName:any,
        public isUnderNotice:any,
        public lastName:any,
        public middleName:any,
        public lastUpdateBy:any,
        public lastUpdatedDate:any,
        public noofPositions:any,
        public noticePeriod:any,
        public position:any,
        public profileType:any,
        public rateCard:any,
        public rateCardCurrency:any,
        public rateCardUom:any,
        public relaventExpMonths:any,
        public relaventExpYears:any,
        public requesitionDate:any,
      //  public requisitionId:any,
        public skills:any,
        public sourceId:any,
        public sourceType:any,
       // public status:any,
        public totalExpMonths:any,
        public totalExpYears:any,
        public requisitionId:any,
        public status:any,
    ){}
}